### ISSUE TITLE
Cannot transfer a local file with spaces in its name

### ISSUE THREAD

**Issue by DoeJoeDE** [GjjvdBurg/paper2remarkable#78] opened 2020-11-27 15:46 UTC
I cannot get it to transfer a local file  with spaces in its name.

Entering something like

`docker run --rm -v "${HOME}/.rmapi:/home/user/.rmapi:rw" -v "$(pwd):/home/user" p2r -v 'example example.pdf'`

throws the following error:

`ERROR: Couldn't figure out what source you mean. If it's a local file, please make sure it exists.`

I already tried both 'example example.pdf' as well as "example example.pdf".

For files without spaces it works completely fine.

I am using p2r with Docker on Windows 10.

**Comment by GjjvdBurg** [comment] 2020-11-27 19:46
Hi @DoeJoeDE, thanks for reporting this.

I can't directly reproduce this since I don't have windows, but perhaps we can debug it together. Have you tried escaping the whitespace using a backslash? The command would be:

```
docker run --rm -v "${HOME}/.rmapi:/home/user/.rmapi:rw" -v "$(pwd):/home/user" p2r -v 'example\ example.pdf'
```

**Comment by DoeJoeDE** [comment] 2020-11-27 20:01
That also does not seem to fix the issue, it still throws the same error message.

I have written a script for myself to simply replace all spaces in the file names, but I am still wondering why it does not work regardless of how I try to account for the spaces.

**Comment by GjjvdBurg** [comment] 2020-11-27 20:14
I suspect it'll have something to do with how docker interprets command line arguments. I can take a look later in the week, but glad you found a work-around in the meantime.

**Comment by GjjvdBurg** [comment] 2020-12-21 17:03
I tried to reproduce this today, but the command provided in the top comment,

```
$ docker run --rm -v "${HOME}/.rmapi:/home/user/.rmapi:rw" -v "$(pwd):/home/user" p2r -v -c -n 'example example.pdf'
```

works on Linux. If someone has ideas on solving this on Windows I'm happy to add it to the readme, but for now there's nothing I can do to solve this as I don't have access to a Windows machine.

**Comment by charlie-cummings** [comment] 2021-01-22 01:04
I use windows but I have an ubuntu subsystem, and that's what I use for p2r. I'd recommend this strongly because Linux has much better documentation for things like this, in a way it's like the best of both worlds if you're like me and prefer Windows for daily computer usage.

**Comment by GjjvdBurg** [comment] 2021-03-01 12:55
I'm closing this as I don't have a Windows system to test on and various workarounds have been proposed. If there's anything to add to the documentation or any other solutions, please reopen the issue.

**Closed by GjjvdBurg** 2021-03-01 12:55 UTC
