### ISSUE TITLE
Hanging on removing timestamp

### ISSUE THREAD

**Issue by philastrophist** [GjjvdBurg/paper2remarkable#111] opened 2021-05-24 11:21 UTC
I've been waiting for an hour for this complete!

```
p2r -v -p /papers/arxiv/24-05-2021/ https://arxiv.org/abs/2105.10474
2021-05-24 10:59:17 - INFO - Starting Arxiv provider
2021-05-24 10:59:17 - INFO - Generating output filename
2021-05-24 10:59:17 - INFO - Getting paper info
2021-05-24 10:59:18 - INFO - Downloaded url: https://arxiv.org/abs/2105.10474
2021-05-24 10:59:18 - INFO - Created filename: Zhang_et_al_-_Trinity_I_Self-Consistently_Modeling_the_Dark_Matter_Halo-Galaxy-Supermassive_Black_Hole_Connection_From_Z_0-10_2021.pdf
2021-05-24 10:59:18 - INFO - Downloading file at url: https://arxiv.org/pdf/2105.10474.pdf
2021-05-24 10:59:31 - INFO - Downloaded url: https://arxiv.org/pdf/2105.10474.pdf
2021-05-24 10:59:31 - INFO - Removing arXiv timestamp ...
```

**Comment by GjjvdBurg** [comment] 2021-05-24 11:41
That's strange, I can't seem to reproduce that:

```
$ p2r -v -n https://arxiv.org/abs/2105.10474
2021-05-24 12:36:55 - INFO - Starting Arxiv provider
2021-05-24 12:36:55 - INFO - Generating output filename
2021-05-24 12:36:55 - INFO - Getting paper info
2021-05-24 12:36:56 - INFO - Downloaded url: https://arxiv.org/abs/2105.10474
2021-05-24 12:36:56 - INFO - Created filename: Zhang_et_al_-_Trinity_I_Self-Consistently_Modeling_the_Dark_Matter_Halo-Galaxy-Supermassive_Black_Hole_Connection_From_Z_0-10_2021.pdf
2021-05-24 12:36:56 - INFO - Downloading file at url: https://arxiv.org/pdf/2105.10474.pdf
2021-05-24 12:37:07 - INFO - Downloaded url: https://arxiv.org/pdf/2105.10474.pdf
2021-05-24 12:37:07 - INFO - Removing arXiv timestamp ... success
2021-05-24 12:39:16 - INFO - Preparing PDF using center operation
2021-05-24 12:39:17 - INFO - Processing pages ... (10/36)
2021-05-24 12:39:23 - INFO - Processing pages ... (20/36)
2021-05-24 12:39:30 - INFO - Processing pages ... (30/36)
2021-05-24 12:39:33 - INFO - Processing pages ... (36/36)
2021-05-24 12:39:33 - INFO - Shrinking pdf file ...
2021-05-24 12:40:12 - INFO - Shrinking has no effect for this file, using original.
```

Are you using pdftk or qpdf?

**Comment by philastrophist** [comment] 2021-05-24 16:51
qpdf and it happens without fail

**Comment by GjjvdBurg** [comment] 2021-05-24 17:28
So, here's what happens: to remove the arXiv stamp reliably we decompress the PDF, remove the stamp and compress it again. However, this particular PDF file decompresses to about 215 MB (probably due to all the pretty plots), which is obviously quite large and therefore time consuming. Why it takes over an hour for you and a few minutes for me I don't know, it might be a hardware difference, but it's quite significant if that's the case. If you have ideas for speeding this up, pull requests are welcome of course. In the meantime, maybe just upload this one using rmapi.

**Comment by philastrophist** [comment] 2021-05-24 17:33
I think I can just get away with a crop for arxiv papers. Does it need to unpack for that as well?

>

**Comment by GjjvdBurg** [comment] 2021-05-24 17:46
Yeah, it might. On closer inspection it seems that the culprit is Ghostscript, which takes about 40 seconds for me and is probably the reason it's slow on your end. This is used to "rewrite" the pdf and to shrink it, and with the ArxivProvider this is actually called 3 times (one of which I think can be eliminated, and I'll leave this issue open to look into that).

Does it take this long for you with all arXiv papers or just this one? If it's just this one you can transfer it to the remarkable and then use the crop tool on the remarkable itself to center the content.

**Comment by philastrophist** [comment] 2021-05-24 18:45
Yeah, it’s just this one (although there actually many like it from arxiv). 
I think if it can’t crop without unpacking/rewriting, I can’t use p2r. I wanted to make crontab script but if it does this then I can’t. 

Oh well, thanks anyway. I’ll upload unmodified

**Comment by GjjvdBurg** [comment] 2021-05-24 18:56
Can you give some other examples that are that slow for you? Might be useful for testing if there are indeed many of them.

**Comment by philastrophist** [comment] 2021-05-24 19:32
Off the top of my from the previous day I've only got two so far the one above and https://arxiv.org/abs/1808.10452.
I believe it's probably the number of points in the plots...

**Comment by GjjvdBurg** [comment] 2021-05-24 20:39
Thanks, it's strange that it takes so long for you, that one takes about 40 seconds for me (although it does unpack to 42MB). What version of Ghostscript do you have? And what platform are you on?

**Comment by GjjvdBurg** [comment] 2021-10-02 10:12
Closing this as I don't think there's much that can be done here. Please reopen if there's more to discuss.

**Closed by GjjvdBurg** 2021-10-02 10:12 UTC
